# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sec_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 370)
        MainWindow.setMinimumSize(QtCore.QSize(560, 370))
        MainWindow.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(160, 10, 681, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_text.setFont(font)
        self.label_text.setStyleSheet("color: rgb(70, 255, 255);")
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.lcdNumber2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber2.setGeometry(QtCore.QRect(395, 95, 161, 61))
        self.lcdNumber2.setStyleSheet("    border: none;\n"
"    outline: none;\n"
"color: rgb(70, 255, 255);\n"
"background-color: rgb(43, 43, 43);")
        self.lcdNumber2.setObjectName("lcdNumber2")
        self.label_text3 = QtWidgets.QLabel(self.centralwidget)
        self.label_text3.setGeometry(QtCore.QRect(160, 310, 681, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text3.setFont(font)
        self.label_text3.setStyleSheet("color:rgb(70, 255, 255);\n"
"")
        self.label_text3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text3.setObjectName("label_text3")
        self.label_text_estimation = QtWidgets.QLabel(self.centralwidget)
        self.label_text_estimation.setGeometry(QtCore.QRect(180, 170, 651, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_text_estimation.setFont(font)
        self.label_text_estimation.setText("")
        self.label_text_estimation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_estimation.setObjectName("label_text_estimation")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 250, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton.setFont(font)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPS Test"))
        self.label_text.setText(_translate("MainWindow", "Ваш кпс:"))
        self.label_text3.setText(_translate("MainWindow", "2022 © CPS Test"))
