# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'third_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 380)
        MainWindow.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_decor = QtWidgets.QLabel(self.centralwidget)
        self.label_decor.setGeometry(QtCore.QRect(0, 0, 70, 380))
        self.label_decor.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.label_decor.setText("")
        self.label_decor.setObjectName("label_decor")
        self.label_decor_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_decor_2.setGeometry(QtCore.QRect(480, 0, 70, 380))
        self.label_decor_2.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.label_decor_2.setText("")
        self.label_decor_2.setObjectName("label_decor_2")
        self.label_4decor = QtWidgets.QLabel(self.centralwidget)
        self.label_4decor.setGeometry(QtCore.QRect(70, 0, 10, 380))
        self.label_4decor.setStyleSheet("background-color: rgb(45, 45, 90);")
        self.label_4decor.setText("")
        self.label_4decor.setObjectName("label_4decor")
        self.label_4decor_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_4decor_2.setGeometry(QtCore.QRect(470, 0, 10, 380))
        self.label_4decor_2.setStyleSheet("background-color: rgb(45, 45, 90);")
        self.label_4decor_2.setText("")
        self.label_4decor_2.setObjectName("label_4decor_2")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(85, 40, 385, 60))    #85, 30, 385, 60
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_text.setFont(font)
        self.label_text.setStyleSheet("color: rgb(70, 255, 255);")
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setObjectName("label_text")
        self.label_text3 = QtWidgets.QLabel(self.centralwidget)
        self.label_text3.setGeometry(QtCore.QRect(80, 330, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text3.setFont(font)
        self.label_text3.setStyleSheet("color:rgb(70, 255, 255);\n"
"")
        self.label_text3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text3.setObjectName("label_text3")
        self.label_2decor = QtWidgets.QLabel(self.centralwidget)
        self.label_2decor.setGeometry(QtCore.QRect(195, 355, 160, 2))
        self.label_2decor.setStyleSheet("background-color:rgb(70, 255, 255);\n"
"")
        self.label_2decor.setText("")
        self.label_2decor.setObjectName("label_2decor")
        self.label_text_estimation_2page = QtWidgets.QLabel(self.centralwidget)
        self.label_text_estimation_2page.setGeometry(QtCore.QRect(80, 200, 390, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_text_estimation_2page.setFont(font)
        self.label_text_estimation_2page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_text_estimation_2page.setStyleSheet("")
        self.label_text_estimation_2page.setText("")
        self.label_text_estimation_2page.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_estimation_2page.setObjectName("label_text_estimation_2page")
        self.lcdNumber2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber2.setGeometry(QtCore.QRect(175, 122, 151, 71))
        self.lcdNumber2.setStyleSheet("border: none;\n"
"color: rgb(70, 255, 255);\n"
"outline: none;")
        self.lcdNumber2.setObjectName("lcdNumber2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 260, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPS Test"))
        self.label_text.setText(_translate("MainWindow", "Кпс пробела:"))
        self.label_text3.setText(_translate("MainWindow", "2022 © CPS Test"))
